### ISSUE TITLE
It allows sending simultaneous request when using a cache store

### ISSUE THREAD

**Issue by bruno-rodrigues** [spatie/guzzle-rate-limiter-middleware#11]
Hey all, thanks for everything you guys do.

Just wanted to let you know that I tried setting up a cache store and dispatching external requests from different terminal windows "at the same time", using 1 request per minute.

It works after the first request is sent but then all other pending requests are dispatched at the same time. 
```
[2020-09-01 12:18:37] local.DEBUG:
REQUEST: GET [redacted] HTTP/1.1
--
[2020-09-01 12:19:37] local.DEBUG:
REQUEST: GET [redacted] HTTP/1.1
--
[2020-09-01 12:19:37] local.DEBUG:
REQUEST: [redacted] HTTP/1.1
--
[2020-09-01 12:19:37] local.DEBUG:
REQUEST: GET [redacted] HTTP/1.1
```

**Comment by dmyers** [comment]
I think you need to use a locking mechanism so that if you were to have PHP processes that ran at the same time somehow it would be only allowable to the limit you set.

**Comment by sebastiandedeyne** [comment]
I agree that this isn't ideal. I'm not actively working on this package anymore, but I'd accept PR's that bring improvements here.
