### ISSUE TITLE
[feat request] allow specifying custom time frames

### ISSUE THREAD

**Issue by rmobis** [spatie/guzzle-rate-limiter-middleware#34]
It would be useful if we were able to specify time frames different than 1 second or 1 minute. The website I'm currently crawling has a 1req/2.5s rate limit, for instance.

**I know this has been previously suggested in #32 over an year ago and was rejected due to backwards compatibility concerns, but my suggestion for a fix would be backwards compatible.**

## Implementation Plan

1. Make `RateLimiter::$timeFrame` a `Carbon\CarbonInterval` (or `DateInterval` if no dependency is preferred)
2. On the constructor, accept both `string|CarbonInterval`, but always convert to `CarbonInterval`
3. Mark `RateLimiter::TIME_FRAME_MINUTE` and `RateLimiter::TIME_FRAME_SECOND` as `@deprecated`
4. Add `RateLimiterMiddleware::perInterval(int $limit, CarbonInterval $interval, ...)`
5. Update `RateLimiterMiddleware::perSecond` and `RateLimiterMiddleware::perMinute` to pass `CarbonInterval`

Constructor would look something like this:

```php
public function __construct(
    protected readonly int $limit,
    CarbonInterval|string $timeFrame,
    protected readonly Store $store,
    protected readonly Deferrer $deferrer
) {
    if (is_string($timeFrame)) {
        $timeFrame = match ($timeFrame) {
            self::TIME_FRAME_MINUTE => CarbonInterval::minute(),
            self::TIME_FRAME_SECOND => CarbonInterval::second(),
            default => CarbonInterval::fromString($timeFrame),
        };
    }

    $this->timeFrame = $timeFrame;
}
```

If that's something you find doable, let me know and I can work on a PR.

**Comment by freekmurze** [comment]
Feel free to create a PR for this. Make sure to include tests and update the readme 👍 Have fun!
